apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogImxpY2Vuc2UtbWFuYWdlciIKICBzY3JhcGVfaW50ZXJ2YWw6IDYwcwogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czogWyJsaWNlbnNlLW1hbmFnZXIubW9uaXRvcmluZzo4NzAwIl0KICAgIGxhYmVsczoKICAgICAgZW52OiAncHJvZHVjdGlvbicKICAgICAgYXBwOiAnbGljZW5zZS1tYW5hZ2VyJwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
