kind: Service
metadata:
  labels:
    app: license-manager
  name: license-manager
  namespace: sre-apps
spec:
  ports:
  - port: 8770
    protocol: TCP
    targetPort: 3000
  selector:
    app: license-manager
status:
  loadBalancer: {}
